### ISSUE TITLE
Dataset module needs fix, tf.image.resize_images not found.

### ISSUE THREAD

**Issue by vishal-keshav** [vishal-keshav/fast_prototype#2]
The dataset module still uses pre-tensorflow 2.0 APIs.

For example, the mnist module in the directory **/dataset/mnist/data_provider.py** is a runnable module to test if dataset provider can fetch the mnist dataset.

Upon executing the module (command: python data_provider.py), I got following error message:

Note: Before I ran the module, I correctly pointed **the raw_path** and **pre_processed_path** to an empty directory (where I want my data to be downloaded and pre_processed).
Refer below snippet:
```
#  raw_path = "/media/bulletcross/VK_SSD/mnist_dataset"
raw_path = "/home/user/empty_dataset_directory"
# pre_processed_path = "/media/bulletcross/VK_SSD/mnist_preprocessed"
pre_processed_path = "/home/user/empty_dataset_directory"
```

The terminal error output is pasted below:
```
Downloading and preparing dataset mnist (11.06 MiB) to /home/vishal/dataset/mnist/1.0.0...
Dl Completed...:   0%|                           /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'storage.googleapis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'storage.googleapis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'storage.googleapis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'storage.googleapis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Dl Completed...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  4.21 url/s]
Extraction completed...: 100%|█████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.39 file/s]
Extraction completed...: 100%|█████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.99 file/s]
Dl Size...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  8.47 MiB/s]

Dl Completed...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.39 url/s]
0 examples [00:00, ? examples/s]2020-03-10 23:30:22.737046: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-10 23:30:22.960150: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2020-03-10 23:30:22.961651: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6587ca0 executing computations on platform Host. Devices:
2020-03-10 23:30:22.961758: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Shuffling...:   0%|                                                                                                      | 0/10 [00:00<?, ? shard/s]WARNING: Logging before flag parsing goes to stderr.
W0310 23:30:43.077329 140641945909056 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/file_format_adapter.py:209: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
Dataset mnist downloaded and prepared to /home/vishal/dataset/mnist/1.0.0. Subsequent calls will reuse this data.                                   
Traceback (most recent call last):                                                                                                                  
  File "data_provider.py", line 150, in <module>
    main()
  File "data_provider.py", line 146, in main
    x,y = obj.get_validation_dataset()
  File "data_provider.py", line 95, in get_validation_dataset
    self.validation_transform)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 1211, in map
    return MapDataset(self, map_func, preserve_cardinality=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3416, in __init__
    use_legacy_function=use_legacy_function)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2695, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1854, in _get_concrete_function_internal
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2689, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2634, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in converted code:

    data_provider.py:47 validation_transform  *
        img = tf.image.resize_images(images = img, size = [28, 28])

    AttributeError: module 'tensorflow_core._api.v2.image' has no attribute 'resize_images'

```

**Comment by vishal-keshav** [comment]
Since the issue has been fixed, I am closing this.
